using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MetricsGenerator;

/// <summary>
/// Incremental source generator that implements methods marked with [Dumper] in classes
/// decorated with [CollectMetrics] and [Metric] attributes.
/// </summary>
[Generator]
public sealed class MetricsSourceGenerator : IIncrementalGenerator
{
    private const string CollectMetricsAttributeFqn = "MetricsGenerator.CollectMetricsAttribute";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Inject the attribute definitions into every compilation that uses this generator.
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("MetricsAttributes.g.cs", AttributeSource));

        // Find classes annotated with [CollectMetrics] and build a model for each one.
        var classProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                CollectMetricsAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetClassModel(ctx))
            .Where(static m => m is not null);

        // Emit a source file for each matched class.
        context.RegisterSourceOutput(classProvider, static (spc, model) =>
        {
            if (model is null) return;
            spc.AddSource($"{model.ClassName}.g.cs", model.GeneratedSource);
        });
    }

    private static ClassModel? GetClassModel(GeneratorAttributeSyntaxContext ctx)
    {
        var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        // Collect all [Metric] attributes on the class.
        var metrics = new List<(string Description, string TypeFullName)>();
        foreach (AttributeData attr in classSymbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name != "MetricAttribute") continue;
            if (attr.ConstructorArguments.Length < 2) continue;

            string description = (string?)attr.ConstructorArguments[0].Value ?? string.Empty;

            if (attr.ConstructorArguments[1].Kind != TypedConstantKind.Type) continue;
            if (attr.ConstructorArguments[1].Value is not INamedTypeSymbol typeSymbol) continue;

            metrics.Add((description, typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
        }

        // Find the first method decorated with [Dumper].
        string? dumperMethodName = null;
        string? accessibility = null;
        foreach (ISymbol member in classSymbol.GetMembers())
        {
            if (member is not IMethodSymbol method || method.MethodKind != MethodKind.Ordinary) continue;

            foreach (AttributeData attr in method.GetAttributes())
            {
                if (attr.AttributeClass?.Name != "DumperAttribute") continue;
                dumperMethodName = method.Name;
                accessibility = method.DeclaredAccessibility switch
                {
                    Accessibility.Public => "public",
                    Accessibility.Internal => "internal",
                    Accessibility.Protected => "protected",
                    Accessibility.Private => "private",
                    _ => "public"
                };
                break;
            }

            if (dumperMethodName is not null) break;
        }

        // Only generate if we have both a [Dumper] method and at least one [Metric].
        if (dumperMethodName is null || metrics.Count == 0) return null;

        string? ns = classSymbol.ContainingNamespace?.IsGlobalNamespace == true
            ? null
            : classSymbol.ContainingNamespace?.ToDisplayString();

        string source = BuildSource(ns, classSymbol.Name, dumperMethodName, accessibility ?? "public", metrics);
        return new ClassModel(classSymbol.Name, source);
    }

    private static string BuildSource(
        string? ns,
        string className,
        string methodName,
        string accessibility,
        List<(string Description, string TypeFullName)> metrics)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    {accessibility} partial void {methodName}()");
        sb.AppendLine("    {");

        foreach ((string description, string typeFullName) in metrics)
        {
            sb.AppendLine($"        System.Console.WriteLine(\"{EscapeString(description)}\");");
            sb.AppendLine($"        System.Console.WriteLine(new {typeFullName}().ToString());");
        }

        sb.AppendLine("    }");
        sb.Append("}");
        return sb.ToString();
    }

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private const string AttributeSource = """
        // <auto-generated/>
        using System;

        namespace MetricsGenerator
        {
            /// <summary>Marks a class as the entry point for metrics collection by the source generator.</summary>
            [AttributeUsage(AttributeTargets.Class)]
            internal sealed class CollectMetricsAttribute : Attribute { }

            /// <summary>Associates a description and a type with the enclosing metrics class.</summary>
            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
            internal sealed class MetricAttribute : Attribute
            {
                /// <summary>Gets the human-readable description of this metric.</summary>
                public string Description { get; }

                /// <summary>Gets the type whose <see cref="object.ToString"/> value will be written to the console.</summary>
                public Type ClassType { get; }

                /// <summary>Initializes a new instance of <see cref="MetricAttribute"/>.</summary>
                /// <param name="description">Human-readable description of the metric.</param>
                /// <param name="classType">Type to instantiate and write to the console.</param>
                public MetricAttribute(string description, Type classType)
                {
                    Description = description;
                    ClassType = classType;
                }
            }

            /// <summary>Marks a partial method that should be implemented by the source generator.</summary>
            [AttributeUsage(AttributeTargets.Method)]
            internal sealed class DumperAttribute : Attribute { }
        }
        """;
}

internal sealed class ClassModel
{
    public ClassModel(string className, string generatedSource)
    {
        ClassName = className;
        GeneratedSource = generatedSource;
    }

    public string ClassName { get; }
    public string GeneratedSource { get; }
}
